#!/bin/bash
###
#
# This is a script to create a simple nicely-formatted track listing from
# a directory of mp3s.  It uses mediainfo in order to parse metadata and writes
# the bbcode-formatted track listing to stdout.
#
###
SCRAPEFILE=$(ls -1 *.{mp3,flac} 2>/dev/null | head -1)

help()
{
cat << EOF
This script will create a BBCode-formatted track list from MP3 or
FLAC files in the current directory.

OPTIONS:
  -h	Show this message
  -s	Use standard artist naming
  -v	Use various artist naming
EOF
}

AARTIST=
ALBUM=
YEAR=
TRACKNO=
ARTIST=
TITLE=
LENGTH=

while getopts ":hvs" OPTION
do
	case $OPTION in
		h)
			help
			exit 1
			;;
		v)
			AARTIST="Various Artists"
			;;
		s)
			AARTIST=`mediainfo -f "$SCRAPEFILE" |
		        grep -i -m 1 "Performer" |
		        sed 's/\(.\{43\}\)//'`
			;;
		?)
			help
			exit 1
			;;
	esac
done

if [[ -z $AARTIST ]]
then
	help
	exit 1
fi

ALBUM=`mediainfo -f "$SCRAPEFILE" |
        grep -i -m 1 "Album" |
        sed 's/\(.\{43\}\)//'`

YEAR=`mediainfo -f "$SCRAPEFILE" |
        grep -i -m 1 "Recorded" |
        sed 's/\(.\{43\}\)//'`

echo "[size=4]"$AARTIST - $ALBUM \($YEAR\)"[/size]"

for afile in *;
    do
        TYPE=$(file -ib "$afile" | cut -f1 -d ' ')
    
        if [[ $TYPE == audio\/mpeg\; || $TYPE == audio\/x\-flac\; ]]
                
        then
            TRACKNO=`mediainfo "$afile" | 
            grep -i -m 1 "track name/position" |
            sed 's/\(.\{43\}\)//'`;
            
            ARTIST=`mediainfo "$afile" |
            grep -i -m 1 "performer" |
            sed 's/\(.\{43\}\)//'`;

            TITLE=`mediainfo "$afile" | 
            grep -i -m 1 "track name"  |
            sed 's/\(.\{43\}\)//'`;

            LENGTH=`mediainfo -f "$afile" |
            grep -i -m 1 ": 00:" | 
            sed 's/\(.\{46\}\)//' | 
            sed 's/....$//'`;
    
            echo "[b]"$TRACKNO".[/b] "$ARTIST - $TITLE \($LENGTH\)
        fi
        done
